### ISSUE TITLE
Error> Too many values to unpack

### ISSUE THREAD

**Issue by ramonsuarez** [barty777/kindle_note_parser#7]
On Ubuntu Linux 16.04 LTS:
`Traceback (most recent call last):
  File "export.py", line 155, in <module>
    main()
  File "export.py", line 135, in main
    sorted(parser_context.parse_raw(args.input_log).items()))
  File "/home/ramon/code/kindle_note_parser/raw_parser/raw_parser.py", line 85, in parse_raw
    return self.strategy.parse_raw(filename=filename)
  File "/home/ramon/code/kindle_note_parser/raw_parser/raw_parser.py", line 50, in parse_raw
    header, book_name, meta, blank, content, footer1 = edit.split('\n')
ValueError: too many values to unpack (expected 6)
`

**Comment by bfreskura** [comment]
@ramonsuarez  I'll need the `My Clippings.txt` file to debug this. Sorry for the late answer.

**Comment by ramonsuarez** [comment]
I'll have to check it again and see if the error is still there. Closing this one.
